//
//  ContinuousCornerProfileIntegrationTests.swift
//  ShapeUpTests
//
//  Created by Ryan Lintott on 2026-08-17.
//

@testable import ShapeUp
import SwiftUI
import Testing

/// Regenerates the sampling positions and weights used by
/// ``ContinuousCornerProfile`` and checks the values it ships against them.
///
/// The library only needs the finished numbers, so it stores them directly.
/// This keeps the recipe that produced them runnable, both to prove those
/// numbers are right and so a different sample count can be generated by
/// calling ``gaussLegendre(count:)`` and pasting in the result.
struct ContinuousCornerProfileIntegrationTests {
    /// The value and slope of the `count`-th Legendre polynomial at `x`.
    ///
    /// Built up one polynomial at a time from `P(0, x) = 1` and `P(1, x) = x`
    /// using `P(n + 1, x) = ((2n + 1) * x * P(n, x) - n * P(n - 1, x)) / (n + 1)`.
    static func legendre(count: Int, at x: Double) -> (value: Double, slope: Double) {
        var previous = 1.0
        var current = x
        for n in 1..<count {
            let next = ((2 * Double(n) + 1) * x * current - Double(n) * previous)
                / (Double(n) + 1)
            previous = current
            current = next
        }
        let slope = Double(count) * (x * current - previous) / (x * x - 1)
        return (current, slope)
    }

    /// Returns where to sample, and how much each sample counts, when adding up
    /// a smooth function across a span running from -1 to 1.
    ///
    /// Each position is a place where the `count`-th Legendre polynomial
    /// crosses zero, found by starting near where it's expected and repeatedly
    /// stepping toward the crossing. Its weight then follows directly from the
    /// polynomial's slope there.
    static func gaussLegendre(count: Int) -> (nodes: [Double], weights: [Double]) {
        var found: [(node: Double, weight: Double)] = []

        for k in 1...count {
            var x = cos(Double.pi * (Double(k) - 0.25) / (Double(count) + 0.5))
            for _ in 0..<100 {
                let (value, slope) = legendre(count: count, at: x)
                let step = -value / slope
                x += step
                if abs(step) < 1e-16 { break }
            }
            let (_, slope) = legendre(count: count, at: x)
            found.append((x, 2 / ((1 - x * x) * slope * slope)))
        }

        found.sort { $0.node < $1.node }
        return (found.map(\.node), found.map(\.weight))
    }

    @Test("The stored sampling positions and weights match the formula")
    func storedValuesMatchTheFormula() throws {
        let expected = Self.gaussLegendre(count: ContinuousCornerProfile.integrationNodes.count)

        try #require(expected.nodes.count == ContinuousCornerProfile.integrationNodes.count)
        try #require(expected.weights.count == ContinuousCornerProfile.integrationWeights.count)

        for (stored, generated) in zip(ContinuousCornerProfile.integrationNodes, expected.nodes) {
            #expect(abs(stored - generated) <= 1e-15)
        }
        for (stored, generated) in zip(ContinuousCornerProfile.integrationWeights, expected.weights) {
            #expect(abs(stored - generated) <= 1e-15)
        }
    }

    @Test(
        "Weights cover the full width of the span they sample",
        arguments: [2, 4, 8, 16, 32]
    )
    func weightsSumToSpanWidth(count: Int) {
        let total = Self.gaussLegendre(count: count).weights.reduce(0, +)

        // The span runs from -1 to 1, so its width is 2.
        #expect(abs(total - 2) <= 1e-12)
    }

    /// Sampling at `count` positions is exact for anything that can be written
    /// as a polynomial up to degree `2 * count - 1`, which is the property that
    /// makes so few samples enough.
    @Test("Sampling is exact for polynomials up to the expected degree")
    func samplingIsExactForPolynomials() {
        let count = ContinuousCornerProfile.integrationNodes.count
        let nodes = ContinuousCornerProfile.integrationNodes
        let weights = ContinuousCornerProfile.integrationWeights

        for degree in 0...(2 * count - 1) {
            let approximated = zip(nodes, weights)
                .reduce(0.0) { $0 + ($1.1 * pow($1.0, Double(degree))) }
            // Integrating x^d from -1 to 1 cancels out for odd powers.
            let exact = degree.isMultiple(of: 2) ? 2 / (Double(degree) + 1) : 0

            #expect(abs(approximated - exact) <= 1e-12)
        }
    }
}
